
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskify-api
    username: postgres
    password: Gagohaso2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api/v1/taskify
security:
  secret:
    key: 532e0960c1082ec81fe81d696b26c6cfbd31949661ae911cc57d82ad1069e4ac