
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskify-api
    username: postgres
    password: Gagohaso2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    validate-on-migrate: true

server:
  servlet:
    context-path: /api/v1/taskify
